url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
lang: "en" # the language of your site
title: "ZeKurity Research Center" # the name of your site, e.g. ACME Corp.
